; -*- mode: lisp; package: user -*-

;;; tiny-segmenter.l
;;
;; Copyright (c) 2008 Taku Kudo <taku@chasen.org>
;; Copyright (c) 2008 MIYAMUKO Katsuyuki <miyamuko@gmail.com>.
;;
;; tiny-segmenter is freely distributable under the terms of a new BSD licence.
;; For details, see http://chasen.org/~taku/software/TinySegmenter/LICENCE.txt
;;

;;; Code:

(in-package :user)

(require "tiny-segmenter/about")
(require "tiny-segmenter/segmenter")


(provide "tiny-segmenter")

;;; End
